/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscritosRouteImport } from './routes/lu4u_9x7a21'
import { Route as IndexRouteImport } from './routes/index'

const InscritosRoute = InscritosRouteImport.update({
  id: 'lu4u_9x7a21',
  path: '/lu4u_9x7a21',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lu4u_9x7a21': typeof InscritosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lu4u_9x7a21': typeof InscritosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lu4u_9x7a21': typeof InscritosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lu4u_9x7a21'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lu4u_9x7a21'
  id: '__root__' | '/' | '/lu4u_9x7a21'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InscritosRoute: typeof InscritosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lu4u_9x7a21': {
      id: '/lu4u_9x7a21'
      path: '/lu4u_9x7a21'
      fullPath: '/lu4u_9x7a21'
      preLoaderRoute: typeof InscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InscritosRoute: InscritosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
